version: '3.9'

services:
  redis_cache:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

  db-data:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: orderdb  
      POSTGRES_USER: user
      POSTGRES_PASSWORD: jeusf23aco3oa9a9a0
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  source-service:
    build: ./source-service
    container_name: source_service
    ports:
      - "50051:50051"
    environment:
      - GRPC_PORT=50051
      - KAFKA_BROKER=kafka:9092
      - MOCK_SERVER_HOST=mock-sources-server
      - MOCK_SERVER_PORT=3629
      - REDIS_HOST=redis_cache
    depends_on:
      - mock-sources-server
      - redis_cache

  outbox-processor:
    build: ./outbox-processor
    container_name: outbox_processor
    environment:
      - MOCK_SERVER_HOST=mock-sources-server
      - MOCK_SERVER_PORT=3629
    depends_on:
      - db-data
      - mock-sources-server
    restart: on-failure:10

  order-service:
    build: ./order-service
    container_name: order_service
    depends_on:
      - db-data
      - outbox-processor
      - source-service
    environment:
      - DATABASE_URL=postgresql://user:jeusf23aco3oa9a9a0@-data:5432/orderdb
      - GRPC_HOST=source_service
      - GRPC_PORT=50051
      - KAFKA_BROKER=kafka:9092
    ports:
      - "8000:8000"

  mock-sources-server:
    build: ./mock-sources-server
    container_name: mock-sources-server
    ports:
      - "3629:3629"

volumes:
  db_data:
