version: '3.9'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka_broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"

  source-service:
    build: ./source-service
    container_name: source_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/orderdb
      - KAFKA_BROKER=kafka_broker:9092
    depends_on:
      - db
      - kafka

  order-service:
    build: ./order-service
    container_name: order_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://user:password@db/orderdb
      - KAFKA_BROKER=kafka_broker:9092
    depends_on:
      - db
      - kafka
      - source-service

volumes:
  db_data:
