# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_client.data_requests_pb2 as data__requests__pb2


class DataRequestsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrderInfo = channel.unary_unary(
                '/datarequests.DataRequestsService/GetOrderInfo',
                request_serializer=data__requests__pb2.GetOrderInfoRequest.SerializeToString,
                response_deserializer=data__requests__pb2.GetOrderInfoResponse.FromString,
                )


class DataRequestsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOrderInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataRequestsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrderInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderInfo,
                    request_deserializer=data__requests__pb2.GetOrderInfoRequest.FromString,
                    response_serializer=data__requests__pb2.GetOrderInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datarequests.DataRequestsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataRequestsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOrderInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datarequests.DataRequestsService/GetOrderInfo',
            data__requests__pb2.GetOrderInfoRequest.SerializeToString,
            data__requests__pb2.GetOrderInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
