# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_requests.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61ta_requests.proto\x12\x0c\x64\x61tarequests\"o\n\nOrderPrice\x12\x18\n\x10\x62\x61se_order_price\x18\x01 \x01(\x02\x12\x11\n\tcoin_coef\x18\x02 \x01(\x02\x12\x19\n\x11\x63oin_bonus_amount\x18\x03 \x01(\x02\x12\x19\n\x11\x66inal_order_price\x18\x04 \x01(\x02\";\n\x0f\x45xecuterProfile\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x02\"<\n\x13GetOrderInfoRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0b\x65xecuter_id\x18\x02 \x01(\t\"\x99\x01\n\x14GetOrderInfoResponse\x12-\n\x0border_price\x18\x01 \x01(\x0b\x32\x18.datarequests.OrderPrice\x12\x19\n\x11zone_display_name\x18\x02 \x01(\t\x12\x37\n\x10\x65xecutor_profile\x18\x03 \x01(\x0b\x32\x1d.datarequests.ExecuterProfile2l\n\x13\x44\x61taRequestsService\x12U\n\x0cGetOrderInfo\x12!.datarequests.GetOrderInfoRequest\x1a\".datarequests.GetOrderInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_requests_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERPRICE']._serialized_start=37
  _globals['_ORDERPRICE']._serialized_end=148
  _globals['_EXECUTERPROFILE']._serialized_start=150
  _globals['_EXECUTERPROFILE']._serialized_end=209
  _globals['_GETORDERINFOREQUEST']._serialized_start=211
  _globals['_GETORDERINFOREQUEST']._serialized_end=271
  _globals['_GETORDERINFORESPONSE']._serialized_start=274
  _globals['_GETORDERINFORESPONSE']._serialized_end=427
  _globals['_DATAREQUESTSSERVICE']._serialized_start=429
  _globals['_DATAREQUESTSSERVICE']._serialized_end=537
# @@protoc_insertion_point(module_scope)
