"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class OrderRequest(google.protobuf.message.Message):
    """Order-related messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: builtins.int
    order_id: builtins.str
    def __init__(
        self,
        *,
        order_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["order_id", b"order_id"]) -> None: ...

global___OrderRequest = OrderRequest

@typing.final
class OrderData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    ZONE_ID_FIELD_NUMBER: builtins.int
    BASE_COIN_AMOUNT_FIELD_NUMBER: builtins.int
    id: builtins.str
    user_id: builtins.str
    zone_id: builtins.str
    base_coin_amount: builtins.float
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        user_id: builtins.str = ...,
        zone_id: builtins.str = ...,
        base_coin_amount: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["base_coin_amount", b"base_coin_amount", "id", b"id", "user_id", b"user_id", "zone_id", b"zone_id"]) -> None: ...

global___OrderData = OrderData

@typing.final
class ZoneRequest(google.protobuf.message.Message):
    """Zone-related messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ZONE_ID_FIELD_NUMBER: builtins.int
    zone_id: builtins.str
    def __init__(
        self,
        *,
        zone_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["zone_id", b"zone_id"]) -> None: ...

global___ZoneRequest = ZoneRequest

@typing.final
class ZoneData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    COIN_COEFF_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    id: builtins.str
    coin_coeff: builtins.float
    display_name: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        coin_coeff: builtins.float = ...,
        display_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["coin_coeff", b"coin_coeff", "display_name", b"display_name", "id", b"id"]) -> None: ...

global___ZoneData = ZoneData

@typing.final
class ExecuterRequest(google.protobuf.message.Message):
    """Executer-related messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXECUTER_ID_FIELD_NUMBER: builtins.int
    executer_id: builtins.str
    def __init__(
        self,
        *,
        executer_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["executer_id", b"executer_id"]) -> None: ...

global___ExecuterRequest = ExecuterRequest

@typing.final
class ExecuterProfile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    RATING_FIELD_NUMBER: builtins.int
    id: builtins.str
    rating: builtins.float
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        tags: collections.abc.Iterable[builtins.str] | None = ...,
        rating: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "rating", b"rating", "tags", b"tags"]) -> None: ...

global___ExecuterProfile = ExecuterProfile

@typing.final
class ConfigData(google.protobuf.message.Message):
    """Configuration-related messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class CoinCoeffSettingsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    COIN_COEFF_SETTINGS_FIELD_NUMBER: builtins.int
    @property
    def coin_coeff_settings(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        coin_coeff_settings: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["coin_coeff_settings", b"coin_coeff_settings"]) -> None: ...

global___ConfigData = ConfigData

@typing.final
class TollRoadsRequest(google.protobuf.message.Message):
    """Toll roads-related messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ZONE_DISPLAY_NAME_FIELD_NUMBER: builtins.int
    zone_display_name: builtins.str
    def __init__(
        self,
        *,
        zone_display_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["zone_display_name", b"zone_display_name"]) -> None: ...

global___TollRoadsRequest = TollRoadsRequest

@typing.final
class TollRoadsData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BONUS_AMOUNT_FIELD_NUMBER: builtins.int
    bonus_amount: builtins.float
    def __init__(
        self,
        *,
        bonus_amount: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bonus_amount", b"bonus_amount"]) -> None: ...

global___TollRoadsData = TollRoadsData
