name: Main workflow

on:
  push:
    branches:
      - main
jobs:
  build_and_push_source_server_to_docker_hub:
    name: Push source-service Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker 
        uses: docker/login-action@v2
        with:
          username: hsecapetown
          password: hsecapetown
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./source-server/
          push: true
          tags: hsecapetown/hse-2024-sd-hw1-source-service:latest

  build_and_push_order_service_to_docker_hub:
    name: Push order-service Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker 
        uses: docker/login-action@v2
        with:
          username: hsecapetown
          password: hsecapetown
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: order-server/
          push: true
          tags: hsecapetown/hse-2024-sd-hw1-order-service:latest
